# Generated by Django 5.2 on 2025-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_history',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=10),
        ),
    ]
